-- Tabla PERSONA
CREATE TABLE EMPLEADO (
    IDEMP NUMBER  NOT NULL ,
    NOMEMP VARCHAR2(100)  NOT NULL,
    APEEMP VARCHAR2(100)  NOT NULL,
    DNIEMP CHAR(8)  NOT NULL,
    SUEEMP NUMBER(6,2)  NOT NULL,
    ESTEMP CHAR(1)  NOT NULL,
    IMAEMP BLOB NULL,
    TIPEMP CHAR(1) NOT NULL,
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (IDEMP)
) ;

-- Creacion de la secuencia
-- secuencia SECUENCIA1
CREATE  SEQUENCE SECUENCIA1 START WITH 1
INCREMENT BY 1;


CREATE OR REPLACE TRIGGER AUTOIDEMPLEADO
BEFORE INSERT ON EMPLEADO
FOR EACH ROW
BEGIN
SELECT SECUENCIA1.NEXTVAL INTO :NEW.IDEMP FROM DUAL;
END;




